MODULE calc_mod
  USE mar_para
  INTEGER, PUBLIC :: NT_F,IRESP

! For ez Tx:
  INTEGER, PUBLIC :: NLU,NLL,CNL,COMP,NLRX
  REAL (OP), PUBLIC :: CZ
  REAL (OP), PUBLIC, DIMENSION(:),ALLOCATABLE :: CTHICK,CANIS
!  COMPLEX (OP), PUBLIC, DIMENSION(:),ALLOCATABLE :: CCON
  REAL (OP), PUBLIC, DIMENSION(:),ALLOCATABLE :: CCON

  REAL (OP), PUBLIC, DIMENSION(:),ALLOCATABLE :: FTIME
  REAL (OP), PUBLIC, DIMENSION(:,:),ALLOCATABLE :: EOUT
! The former threel common block
  REAL (OP), PUBLIC :: C(12),AMU,AT,CRHO,CDSEA
! The former besint common block
!  IF NEW.GT.0, COMMON /BESINT/ CONTAINS THE KERNEL FUNCTION ARGUMENTS 
!  AND VALUES KARG(I,N),KERN(I,N) FOR N=1 TO NPS AND I=1 TO
!  2**(NK(N)+1)-1.
!  KERN(I,N), KERN(I+1,N) CONTAIN THE REAL AND IMAGINARY PARTS OF THE
!  KERNEL FUNCTION FOR THE CORRESPONDING ARGUMENT VALUE KARG(I,N).
!  EACH VALUE OF N CORRESPONDS TO ONE ENTRY IN XSUM OR TO ONE INTERVAL
!  BETWEEN ZERO CROSSINGS OF THE BESSEL FUNCTION DIVIDED BY NPCS.
!  NOTE THAT UP TO NTERM VALUES ARE STORED THE INTEGRATION PROCEEDS
!  FOR N.GT.NTERM AS IF NEW=0. NP IS AN INDEX PASSED INTERNALLY BY
!  BESTRN.
  INTEGER, PUBLIC, PARAMETER :: NTERM=100, NSTOP=100
  INTEGER, PUBLIC :: NK(NTERM),NP,NPS
  REAL (OP), PUBLIC :: KARG(255,NTERM),KERN(510,NTERM),OMEGA

! NC_FRT = Number of filter coefficents (Fast Hankel Transform)
  REAL (OP), PUBLIC, PARAMETER :: SQRT2PI=0.7978845608_OP
  REAL (OP), PUBLIC, PARAMETER :: QSHIFT10=0.8288642172080_OP
  INTEGER, PUBLIC, PARAMETER :: NC0_FRT10=48 ! # of filter coefficients for FRT
  INTEGER, PUBLIC, PARAMETER :: NC_FRT10=80 ! # of filter coefficients for FRT

  INTEGER, PUBLIC, PARAMETER :: NC0_FRT8=36 ! # of filter coefficients for FRT
  INTEGER, PUBLIC, PARAMETER :: NC_FRT8=60 ! # of filter coefficients for FRT

  REAL (OP), PUBLIC, PARAMETER :: SQRT10 = 1.258925411794167_OP
  REAL (OP), PUBLIC, PARAMETER :: PI=3.141592653589793_OP
  INTEGER,PUBLIC,PARAMETER :: NC0_FRT=NC0_FRT10 ! # of filter coefficients for FRT
  INTEGER,PUBLIC,PARAMETER :: NC_FRT=NC_FRT10 ! # of filter coefficients for FRT
  REAL (OP), PUBLIC, PARAMETER :: QSHIFT=QSHIFT10

  LOGICAL,PUBLIC::NND

  INTEGER, PUBLIC, PARAMETER :: NYYP=61,NRRP=81
END MODULE calc_mod
