MODULE mar_para
  CHARACTER(LEN=5),PUBLIC,PARAMETER :: VER='0.99'
  INTEGER,PUBLIC,PARAMETER :: FVER=3
  INTEGER,PUBLIC,PARAMETER :: OP=SELECTED_REAL_KIND(15,307)
  INTEGER,PUBLIC,PARAMETER :: SP=SELECTED_REAL_KIND(6,37)

! Machine dependent values:
  REAL (OP),PUBLIC :: ETA,TOL
! Settings for the forward calculation
  INTEGER,PUBLIC :: DIPOLE_PARTS

END MODULE mar_para
